# def greeting(name):
#     print("Hello " + name)

# greeting("gul")

# def func():
#     print("Hello From GUL!")

# func()    

# def CalculateGmean(a,b):
#     mean = a*b/a+b
#     print(mean)
# a = 2
# b = 3
# c = 4
# d = 8
# CalculateGmean(c,d)
# CalculateGmean(a,b)

# def Greater(a,b):
#     if(a>b):
#         print("a is Greater")
#     else:
#         print("b is Greater ")

# Greater(2,12)
# Greater(3,2)

# def evenODD(x):
#     if (x%2)== 0:
#       print(" x is even")
#     else:
#        print("x is odd")

# evenODD(5)
# evenODD(6)

# def name(fname,lname):
#     print(fname, lname)

# name("Harvinder", "Kaur")    

print(ab+ab)